import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/providers/ThemeProvider";
import { Web3Provider } from "@/providers/Web3Provider";
import { GlowCursor } from "@/components/GlowCursor";
import { SocialLinksHolo } from "@/components/SocialLinksHolo";
import { DownloadResumeHolo } from "@/components/DownloadResumeHolo";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider>
          <Web3Provider>
            {children}
            <GlowCursor />
            <SocialLinksHolo />
            <DownloadResumeHolo />
          </Web3Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
